jobs:
  build:
    working_directory: ~/dobtco/screendoor-api-docs
    parallelism: 1
    docker:
      # https://hub.docker.com/r/circleci/ruby/tags/
      - image: circleci/ruby:2.3.7-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: circleci
          RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: Environment Variables
          command: printenv
          background: true
      - run:
          name: RubyGems
          command: gem env
          background: true
      - run:
          name: Bundler version
          command: bundle --version
          background: true
      - run:
          name: NPM version
          command: npm version
          background: true
      # https://circleci.com/docs/2.0/caching/
      # Restore bundle cache
      - restore_cache:
          key: screendoor-api-docs-cache-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle install
          command: bundle check || bundle install
      # Cache bundle
      - save_cache:
          key: screendoor-api-docs-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      # Restore NPM Cache
      - restore_cache:
          key: screendoor-api-docs-cache-{{ checksum "package.json" }}
      - run:
          name: Install grunt-cli
          command: npm install grunt-cli
      - run:
          name: Install dependencies
          command: npm install
      # Cache node modules
      - save_cache:
          key: screendoor-api-docs-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run cibuild test script
          command: script/cibuild
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_test_results:
          path: test-results.xml
  deploy_production:
    docker:
      - image: circleci/ruby:2.3.7-node-browsers
    working_directory: ~/dobtco/screendoor-api-docs
    steps:
      - checkout
      - restore_cache:
          key: screendoor-api-docs-cache-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle install
          command: bundle check || bundle install
      - restore_cache:
          key: screendoor-api-docs-cache-{{ checksum "package.json" }}
      - run:
          name: Install grunt-cli
          command: npm install grunt-cli
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Deploy
          command: |
            git config --global user.email "ops@dobt.co"
            git config --global user.name "CircleCI"
            script/deploy
workflows:
  version: 2
  build_and_maybe_deploy:
    jobs:
      - build
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only:
                - master
